[package]
name = "nimbus-sdk-kms"
version = "0.1.0"
edition = "2021"
description = "Nimbus kms Rust SDK"
license = "Apache-2.0"

[dependencies]
nimbus-sdk-core = { path = ".." }
serde = { workspace = true }
serde_json = { workspace = true }
